# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Nginx Deployment

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wazuh-nginx
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-nginx
  template:
    metadata:
      labels:
        app: wazuh-nginx
      name: wazuh-nginx
    spec:
      containers:
        - name: wazuh-nginx
          image: 'wazuh/wazuh-nginx:3.13.1_7.8.0'
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: NGINX_PORT
              value: '443'
              #  - name: NGINX_NAME
              #  value: 'foo'
              # - name: NGINX_PWD
              # value: 'bar'
          envFrom:
          - secretRef:
              name: nginx
          ports:
            - containerPort: 80
            - containerPort: 443
